import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  FileText,
  Shield,
  ShoppingCart,
  Award,
  ArrowRight,
  CheckCircle2,
} from "lucide-react";
import { Link } from "react-router-dom";
import howItWorksImg from "@/assets/how-it-works.jpg";

const HowItWorks = () => {
  const steps = [
    {
      number: "01",
      icon: FileText,
      title: "Project Registration",
      description:
        "Environmental projects that reduce or remove CO₂ emissions register with international registries like UCR, Verra, or Gold Standard.",
      details: [
        "Project documentation submitted",
        "Baseline emissions calculated",
        "Methodology approved",
        "Monitoring plan established",
      ],
    },
    {
      number: "02",
      icon: Shield,
      title: "Third-Party Verification",
      description:
        "Independent verifiers audit the project to ensure it meets strict standards and achieves actual, measurable emission reductions.",
      details: [
        "On-site inspection conducted",
        "Emission reductions verified",
        "Additionality confirmed",
        "Verification report issued",
      ],
    },
    {
      number: "03",
      icon: Award,
      title: "Credit Issuance",
      description:
        "Upon verification, carbon credits are issued by the registry. Each credit represents one ton of CO₂ reduced or removed from the atmosphere.",
      details: [
        "Credits issued by registry",
        "Unique serial numbers assigned",
        "Listed on Offst.AI marketplace",
        "Available for trading",
      ],
    },
    {
      number: "04",
      icon: ShoppingCart,
      title: "Trading & Purchase",
      description:
        "Buyers browse verified projects and purchase credits through our secure marketplace with transparent pricing and instant settlement.",
      details: [
        "Browse verified projects",
        "Compare prices and impact",
        "Secure transaction processing",
        "Credits transferred to wallet",
      ],
    },
    {
      number: "05",
      icon: CheckCircle2,
      title: "Retirement & Certification",
      description:
        "Credits are retired to offset emissions, ensuring they can't be reused. Digital certificates with QR codes prove the environmental impact.",
      details: [
        "Credits permanently retired",
        "Registry records updated",
        "Digital certificate generated",
        "Impact tracked and reported",
      ],
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      {/* Hero Section - Enhanced */}
      <section className="relative bg-gradient-to-br from-primary via-primary/95 to-primary/90 py-24 overflow-hidden">
        {/* Background Effects */}
        <div className="absolute inset-0">
          <div className="absolute top-20 left-20 w-72 h-72 bg-primary-light/20 rounded-full blur-3xl animate-pulse" />
          <div className="absolute bottom-20 right-20 w-96 h-96 bg-accent/20 rounded-full blur-3xl animate-pulse" style={{ animationDelay: "1s" }} />
        </div>
        
        <div className="container relative mx-auto px-4 text-center">
          <Badge className="mb-6 bg-white/20 text-white backdrop-blur-md border-white/30 px-4 py-2 animate-fade-in">
            Understanding Carbon Credits
          </Badge>
          <h1 className="mb-6 text-5xl font-bold text-white md:text-6xl animate-fade-in" style={{ animationDelay: "0.1s" }}>
            How Carbon Credits Work
          </h1>
          <p className="mx-auto max-w-3xl text-xl text-white/95 leading-relaxed animate-fade-in" style={{ animationDelay: "0.2s" }}>
            A transparent, verified process from project creation to environmental impact. 
            Learn how carbon credits help fight climate change step by step.
          </p>
        </div>
      </section>

      {/* Introduction */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="mx-auto grid max-w-6xl grid-cols-1 items-center gap-12 lg:grid-cols-2">
            <div>
              <h2 className="mb-6 text-3xl font-bold text-foreground">
                What Are Carbon Credits?
              </h2>
              <p className="mb-4 text-muted-foreground">
                A carbon credit is a tradable certificate representing the reduction or removal of one 
                metric ton of carbon dioxide (CO₂) or an equivalent amount of other greenhouse gases from 
                the atmosphere.
              </p>
              <p className="mb-6 text-muted-foreground">
                These credits are generated by environmental projects—such as renewable energy installations, 
                reforestation initiatives, or energy efficiency programs—that demonstrably reduce emissions 
                compared to a baseline scenario.
              </p>
              <div className="space-y-3">
                {[
                  "Verified by independent third parties",
                  "Tracked by international registries",
                  "Permanent and non-duplicatable",
                  "Measurable environmental impact",
                ].map((point, index) => (
                  <div key={index} className="flex items-start gap-3">
                    <CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-success" />
                    <span className="text-sm text-muted-foreground">{point}</span>
                  </div>
                ))}
              </div>
            </div>
            <div>
              <img
                src={howItWorksImg}
                alt="Carbon credits process"
                className="rounded-2xl shadow-xl"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Process Steps */}
      <section className="bg-muted/30 py-16">
        <div className="container mx-auto px-4">
          <div className="mb-12 text-center">
            <h2 className="mb-4 text-3xl font-bold text-foreground md:text-4xl">
              The Carbon Credit Lifecycle
            </h2>
            <p className="mx-auto max-w-2xl text-muted-foreground">
              From project development to environmental impact - a step-by-step guide
            </p>
          </div>

          <div className="mx-auto max-w-4xl space-y-8">
            {steps.map((step, index) => (
              <Card
                key={index}
                className="overflow-hidden border-border bg-card transition-all hover:shadow-lg"
              >
                <div className="flex flex-col md:flex-row">
                  <div className="flex items-center justify-center bg-primary/10 p-8 md:w-32">
                    <div className="text-center">
                      <p className="mb-2 text-4xl font-bold text-primary">{step.number}</p>
                      <step.icon className="mx-auto h-8 w-8 text-primary" />
                    </div>
                  </div>
                  <div className="flex-1 p-6">
                    <h3 className="mb-3 text-xl font-semibold text-foreground">
                      {step.title}
                    </h3>
                    <p className="mb-4 text-muted-foreground">{step.description}</p>
                    <ul className="space-y-2">
                      {step.details.map((detail, idx) => (
                        <li key={idx} className="flex items-start gap-2">
                          <div className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                          <span className="text-sm text-muted-foreground">{detail}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Registries Section */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-4xl text-center">
            <h2 className="mb-6 text-3xl font-bold text-foreground md:text-4xl">
              Trusted International Registries
            </h2>
            <p className="mb-8 text-muted-foreground">
              All projects on Offst.AI are verified by internationally recognized registries
            </p>
            <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
              {["UCR", "Verra VCS", "Gold Standard"].map((registry) => (
                <Card key={registry} className="border-border bg-card p-8">
                  <h3 className="text-xl font-semibold text-foreground">{registry}</h3>
                  <p className="mt-2 text-sm text-muted-foreground">
                    International Standard
                  </p>
                </Card>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-gradient-hero py-16">
        <div className="container mx-auto px-4 text-center">
          <h2 className="mb-4 text-3xl font-bold text-primary-foreground md:text-4xl">
            Ready to Get Started?
          </h2>
          <p className="mx-auto mb-8 max-w-2xl text-lg text-primary-foreground/90">
            Join Offst.AI today and start making a measurable impact on climate change
          </p>
          <div className="flex flex-col gap-4 sm:flex-row sm:justify-center">
            <Button variant="hero" size="xl" asChild className="bg-card text-foreground hover:bg-card/90">
              <Link to="/marketplace">
                Browse Projects <ArrowRight className="ml-2 h-5 w-5" />
              </Link>
            </Button>
            <Button variant="outline-primary" size="xl" asChild className="border-primary-foreground text-primary-foreground hover:bg-primary-foreground/10">
              <Link to="/signup">Create Account</Link>
            </Button>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default HowItWorks;
